package frontend;

import backend.Aplicacao;
import backend.Serializacao;
import backend.entidades.Administrador;
import frontend.janelas.JanelaConsultaEnfermaria;
import frontend.janelas.JanelaConsultaEquipamento;
import frontend.janelas.JanelaConsultaHospital;
import frontend.janelas.JanelaConsultaPaciente;
import frontend.janelas.JanelaConsultaUtilizador;

public class Homepage extends javax.swing.JFrame {

    private static Aplicacao app;
    private static Serializacao serializacao;

    Homepage(Aplicacao app, Serializacao serializacao) {
        this.app = app;
        this.serializacao = serializacao;

        initComponents();
        //Força a maximização da janela
//        this.setExtendedState(Homepage.MAXIMIZED_BOTH);    

        //O processo de fecho da janela será controlado pelo programa
        this.setDefaultCloseOperation(EXIT_ON_CLOSE);

        //Apenas mostra o menu de administração se o utilizador for um administrador
        menuAdmin.setVisible(app.getUtilizadorAutenticado() instanceof Administrador);

        //Mostra o menu Iniciar
        menuIniciar.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        hospital1 = new backend.entidades.Hospital();
        hospital2 = new backend.entidades.Hospital();
        popupMenu1 = new java.awt.PopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAdmin = new javax.swing.JMenu();
        menuAcessoLogout = new javax.swing.JMenuItem();
        menuAcessoLogin = new javax.swing.JMenuItem();
        menuAcessoGerirUtilizadores = new javax.swing.JMenuItem();
        menuEditarPerfil = new javax.swing.JMenuItem();
        menuIniciar = new javax.swing.JMenu();
        menuListarHospitais = new javax.swing.JMenuItem();
        meniListarEnfermarias = new javax.swing.JCheckBoxMenuItem();
        meniListarEquipamentos = new javax.swing.JMenuItem();
        menuListarProfissionaisSaude = new javax.swing.JMenuItem();
        menuListarPacientes = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        menuAdmin.setText("Administrador");
        menuAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAdminActionPerformed(evt);
            }
        });

        menuAcessoLogout.setText("Login");
        menuAcessoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoLogoutActionPerformed(evt);
            }
        });
        menuAdmin.add(menuAcessoLogout);

        menuAcessoLogin.setText("Logout");
        menuAcessoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoLoginActionPerformed(evt);
            }
        });
        menuAdmin.add(menuAcessoLogin);

        menuAcessoGerirUtilizadores.setText("Gerir Utilizadores");
        menuAcessoGerirUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoGerirUtilizadoresActionPerformed(evt);
            }
        });
        menuAdmin.add(menuAcessoGerirUtilizadores);

        menuEditarPerfil.setText("Editar Perfil");
        menuEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarPerfilActionPerformed(evt);
            }
        });
        menuAdmin.add(menuEditarPerfil);

        jMenuBar1.add(menuAdmin);

        menuIniciar.setText("Iniciar");

        menuListarHospitais.setText("Hospitais");
        menuListarHospitais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarHospitaisActionPerformed(evt);
            }
        });
        menuIniciar.add(menuListarHospitais);

        meniListarEnfermarias.setText("Enfermarias");
        meniListarEnfermarias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniListarEnfermariasActionPerformed(evt);
            }
        });
        menuIniciar.add(meniListarEnfermarias);

        meniListarEquipamentos.setText("Equipamentos");
        meniListarEquipamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                meniListarEquipamentosActionPerformed(evt);
            }
        });
        menuIniciar.add(meniListarEquipamentos);

        menuListarProfissionaisSaude.setText("Profissionais de Saúde");
        menuListarProfissionaisSaude.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarProfissionaisSaudeActionPerformed(evt);
            }
        });
        menuIniciar.add(menuListarProfissionaisSaude);

        menuListarPacientes.setText("Pacientes");
        menuListarPacientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuListarPacientesMouseClicked(evt);
            }
        });
        menuListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuListarPacientesActionPerformed(evt);
            }
        });
        menuIniciar.add(menuListarPacientes);

        jMenuBar1.add(menuIniciar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAcessoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoLogoutActionPerformed

    }//GEN-LAST:event_menuAcessoLogoutActionPerformed

    private void menuAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAdminActionPerformed

    private void menuAcessoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcessoLoginActionPerformed

    private void menuAcessoGerirUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoGerirUtilizadoresActionPerformed
        listarUtilizadores();
    }//GEN-LAST:event_menuAcessoGerirUtilizadoresActionPerformed

    private void menuEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarPerfilActionPerformed

    private void menuListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarPacientesActionPerformed
        listarPacientes();
    }//GEN-LAST:event_menuListarPacientesActionPerformed

    private void meniListarEnfermariasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniListarEnfermariasActionPerformed
        listarEnfermarias();
    }//GEN-LAST:event_meniListarEnfermariasActionPerformed

    private void menuListarHospitaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarHospitaisActionPerformed
        listarHospitais();
    }//GEN-LAST:event_menuListarHospitaisActionPerformed

    private void menuListarProfissionaisSaudeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuListarProfissionaisSaudeActionPerformed
        listarProfissionaisSaude();
    }//GEN-LAST:event_menuListarProfissionaisSaudeActionPerformed

    private void meniListarEquipamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_meniListarEquipamentosActionPerformed
        listarEquipamentos();
    }//GEN-LAST:event_meniListarEquipamentosActionPerformed

    private void menuListarPacientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuListarPacientesMouseClicked
        listarPacientes();
    }//GEN-LAST:event_menuListarPacientesMouseClicked

    /**
     * // * @param args the command line arguments //
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Homepage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private backend.entidades.Hospital hospital1;
    private backend.entidades.Hospital hospital2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JCheckBoxMenuItem meniListarEnfermarias;
    private javax.swing.JMenuItem meniListarEquipamentos;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private javax.swing.JMenuItem menuAcessoGerirUtilizadores;
    private javax.swing.JMenuItem menuAcessoLogin;
    private javax.swing.JMenuItem menuAcessoLogout;
    private javax.swing.JMenu menuAdmin;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem menuEditarPerfil;
    private javax.swing.JMenu menuIniciar;
    private javax.swing.JMenuItem menuListarHospitais;
    private javax.swing.JMenuItem menuListarPacientes;
    private javax.swing.JMenuItem menuListarProfissionaisSaude;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables

    private void listarHospitais() {
        JanelaConsultaHospital janelaConsulta = new JanelaConsultaHospital(app, serializacao);
        janelaConsulta.setVisible(true);
    }

    private void listarEnfermarias() {
        JanelaConsultaEnfermaria janelaConsulta = new JanelaConsultaEnfermaria(app, serializacao);
        janelaConsulta.setVisible(true);
    }

    private void listarEquipamentos() {
        JanelaConsultaEquipamento janelaConsulta = new JanelaConsultaEquipamento(app, serializacao);
        janelaConsulta.setVisible(true);
    }

    private void listarProfissionaisSaude() {
        // TODO
    }

    private void listarPacientes() {
        JanelaConsultaPaciente janelaConsulta = new JanelaConsultaPaciente(app, serializacao);
        janelaConsulta.setVisible(true);
    }

    private void listarUtilizadores() {
        JanelaConsultaUtilizador janelaConsulta = new JanelaConsultaUtilizador(app, serializacao);
        janelaConsulta.setVisible(true);
    }
}
