package frontend;

import backend.Aplicacao;
import backend.Serializacao;
import backend.managers.ManagerEnfermaria;
import frontend.janelas.JanelaConsultaEnfermaria;

public class Homepage extends javax.swing.JFrame {

    private static Aplicacao app;
    private static Serializacao serializacao;

    Homepage(Aplicacao app, Serializacao serializacao) {
        this.app = app;
        this.serializacao = serializacao;

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        hospital1 = new backend.entidades.Hospital();
        hospital2 = new backend.entidades.Hospital();
        popupMenu1 = new java.awt.PopupMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuAcesso = new javax.swing.JMenu();
        menuAcessoLogout = new javax.swing.JMenuItem();
        menuAcessoLogin = new javax.swing.JMenuItem();
        menuAcessoGerirUtilizadores = new javax.swing.JMenuItem();
        menuEditarPerfil = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenu();
        menuAbrirHospitais = new javax.swing.JMenuItem();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        menuAbrirEquipamentos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuAbrirPacientes = new javax.swing.JMenuItem();
        menuCamas = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        popupMenu1.setLabel("popupMenu1");

        jMenu3.setText("jMenu3");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jTable1);

        menuAcesso.setText("Acesso");
        menuAcesso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoActionPerformed(evt);
            }
        });

        menuAcessoLogout.setText("Login");
        menuAcessoLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoLogoutActionPerformed(evt);
            }
        });
        menuAcesso.add(menuAcessoLogout);

        menuAcessoLogin.setText("Logout");
        menuAcessoLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoLoginActionPerformed(evt);
            }
        });
        menuAcesso.add(menuAcessoLogin);

        menuAcessoGerirUtilizadores.setText("Gerir Utilizadores");
        menuAcessoGerirUtilizadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAcessoGerirUtilizadoresActionPerformed(evt);
            }
        });
        menuAcesso.add(menuAcessoGerirUtilizadores);

        menuEditarPerfil.setText("Editar Perfil");
        menuEditarPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuEditarPerfilActionPerformed(evt);
            }
        });
        menuAcesso.add(menuEditarPerfil);

        jMenuBar1.add(menuAcesso);

        menuAbrir.setText("Abrir");

        menuAbrirHospitais.setText("Hospitais");
        menuAbrir.add(menuAbrirHospitais);

        jCheckBoxMenuItem1.setText("Enfermarias");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        menuAbrir.add(jCheckBoxMenuItem1);

        menuAbrirEquipamentos.setText("Equipamentos");
        menuAbrir.add(menuAbrirEquipamentos);

        jMenuItem2.setText("Profissionais de Saúde");
        menuAbrir.add(jMenuItem2);

        menuAbrirPacientes.setText("Pacientes");
        menuAbrirPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbrirPacientesActionPerformed(evt);
            }
        });
        menuAbrir.add(menuAbrirPacientes);

        menuCamas.setText("Camas");
        menuAbrir.add(menuCamas);

        jMenuBar1.add(menuAbrir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 722, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAcessoLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoLogoutActionPerformed
        
    }//GEN-LAST:event_menuAcessoLogoutActionPerformed

    private void menuAcessoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcessoActionPerformed

    private void menuAcessoLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcessoLoginActionPerformed

    private void menuAcessoGerirUtilizadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAcessoGerirUtilizadoresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAcessoGerirUtilizadoresActionPerformed

    private void menuEditarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuEditarPerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuEditarPerfilActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
        JanelaConsultaEnfermaria janelaConsulta = new JanelaConsultaEnfermaria(app, serializacao);
        janelaConsulta.setVisible(true);
    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void menuAbrirPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirPacientesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menuAbrirPacientesActionPerformed

    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Homepage().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private backend.entidades.Hospital hospital1;
    private backend.entidades.Hospital hospital2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private javax.swing.JMenu menuAbrir;
    private javax.swing.JMenuItem menuAbrirEquipamentos;
    private javax.swing.JMenuItem menuAbrirHospitais;
    private javax.swing.JMenuItem menuAbrirPacientes;
    private javax.swing.JMenu menuAcesso;
    private javax.swing.JMenuItem menuAcessoGerirUtilizadores;
    private javax.swing.JMenuItem menuAcessoLogin;
    private javax.swing.JMenuItem menuAcessoLogout;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JMenuItem menuCamas;
    private javax.swing.JMenuItem menuEditarPerfil;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
